### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by esteriella** [PrincessMaggy/africhow#39]
Routes are working in localhost but not on the deployed app.
Example instances:

Working: http://localhost:5173/store-overview 
![Screenshot (22)](https://github.com/PrincessMaggy/africhow/assets/118930791/148ddcb1-cbcf-40ce-ac21-ee229edb7bab)

Not working and returning not found: https://africhow.vercel.app/store-overview
![Screenshot (20)](https://github.com/PrincessMaggy/africhow/assets/118930791/0dd10621-bb0f-4c9e-95c3-8e8b42a707f2)

Not working and returning not found: https://esteriella-africhow.vercel.app/store-overview
![Screenshot (21)](https://github.com/PrincessMaggy/africhow/assets/118930791/369e4524-fed0-4724-bed5-45b3fb77eb01)

This error applies to every path except the home path.

**Comment by PrincessMaggy** [comment]
I'll have a look at this. Thanks

**Comment by PrincessMaggy** [comment]
It's working properly from my end.
